In [1]:
from tensorflow import keras
import matplotlib.pyplot as plt

In [2]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import numpy as np

In [3]:
import cv2
from sklearn import metrics

In [4]:
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

170508288/170498071 [==============================] - 4s 0us/step


In [5]:
x_train.shape,x_test.shape

((50000, 32, 32, 3), (10000, 32, 32, 3))

In [6]:
# Normalization
x_train = x_train/255.0
x_test = x_test/255.0

In [7]:
nsamples, nx, ny, nrgb = x_train.shape
x_train2 = x_train.reshape((nsamples,nx*ny*nrgb))
x_train2

array([[0.23137255, 0.24313725, 0.24705882, ..., 0.48235294, 0.36078431,
        0.28235294],
       [0.60392157, 0.69411765, 0.73333333, ..., 0.56078431, 0.52156863,
        0.56470588],
       [1.        , 1.        , 1.        , ..., 0.31372549, 0.3372549 ,
        0.32941176],
       ...,
       [0.1372549 , 0.69803922, 0.92156863, ..., 0.04705882, 0.12156863,
        0.19607843],
       [0.74117647, 0.82745098, 0.94117647, ..., 0.76470588, 0.74509804,
        0.67058824],
       [0.89803922, 0.89803922, 0.9372549 , ..., 0.63921569, 0.63921569,
        0.63137255]])

In [8]:
nsamples, nx, ny, nrgb = x_test.shape
x_test2 = x_test.reshape((nsamples,nx*ny*nrgb))
x_test2

array([[0.61960784, 0.43921569, 0.19215686, ..., 0.08235294, 0.2627451 ,
        0.43137255],
       [0.92156863, 0.92156863, 0.92156863, ..., 0.72941176, 0.78431373,
        0.78039216],
       [0.61960784, 0.74509804, 0.87058824, ..., 0.02745098, 0.03137255,
        0.02745098],
       ...,
       [0.07843137, 0.05882353, 0.04705882, ..., 0.09803922, 0.07843137,
        0.18431373],
       [0.09803922, 0.15686275, 0.04705882, ..., 0.36078431, 0.47058824,
        0.31372549],
       [0.28627451, 0.30588235, 0.29411765, ..., 0.10588235, 0.10196078,
        0.10196078]])

In [9]:
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [10]:
from sklearn.ensemble import RandomForestClassifier

In [14]:
model=RandomForestClassifier()

In [15]:
model.fit(x_train2,y_train.ravel())

RandomForestClassifier()

In [16]:
y_pred=model.predict(x_test2)
y_pred

array([4, 8, 8, ..., 3, 5, 7], dtype=uint8)

In [17]:
#Random Forest Classifier
accuracy_score(y_pred,y_test)
print('Accuracy Score: ',accuracy_score)
print(classification_report(y_pred,y_test))
cm1 =confusion_matrix(y_pred,y_test)
print('Confusion Matrix: ',cm1)

Accuracy Score:  <function accuracy_score at 0x7f7ccc77c5f0>
              precision    recall  f1-score   support

           0       0.55      0.54      0.54      1031
           1       0.54      0.50      0.52      1090
           2       0.34      0.39      0.36       877
           3       0.28      0.35      0.31       810
           4       0.42      0.42      0.42      1002
           5       0.40      0.43      0.41       929
           6       0.56      0.47      0.52      1190
           7       0.45      0.50      0.47       887
           8       0.61      0.58      0.60      1066
           9       0.53      0.48      0.50      1118

    accuracy                           0.47     10000
   macro avg       0.47      0.46      0.47     10000
weighted avg       0.48      0.47      0.47     10000

Confusion Matrix:  [[553  31 107  56  54  36  11  47  89  47]
 [ 39 542  38  48  30  33  36  54  96 174]
 [ 55  15 340  71 146  85  87  47  17  14]
 [ 13  31  78 281  53 139  79  6

In [18]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=7)
knn.fit(x_train2,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=7)

In [19]:
y_pred_knn = knn.predict(x_test2)
y_pred_knn

array([2, 8, 8, ..., 5, 6, 4], dtype=uint8)

In [20]:
#K Nearest Neighbours
accuracy_score(y_pred_knn,y_test)
print('Accuracy Score: ',accuracy_score)
print(classification_report(y_pred_knn,y_test))
cm2 = confusion_matrix(y_pred_knn,y_test)
print('Confusion Matrix: ',cm2)

Accuracy Score:  <function accuracy_score at 0x7f7ccc77c5f0>
              precision    recall  f1-score   support

           0       0.52      0.40      0.45      1299
           1       0.20      0.70      0.30       280
           2       0.44      0.22      0.29      2013
           3       0.20      0.28      0.23       707
           4       0.52      0.23      0.32      2222
           5       0.20      0.40      0.27       504
           6       0.27      0.35      0.30       761
           7       0.20      0.70      0.31       281
           8       0.69      0.39      0.50      1749
           9       0.14      0.73      0.23       184

    accuracy                           0.34     10000
   macro avg       0.34      0.44      0.32     10000
weighted avg       0.45      0.34      0.35     10000

Confusion Matrix:  [[518 118 110  66  60  63  22  78 112 152]
 [  7 195   2   5   0   2   1   8  10  50]
 [118 124 437 243 268 225 271 185  47  95]
 [ 12  51  50 199  33 156  56  5